---

- name: check grub file # task name
  shell: test -f /boot/grub/menu.lst # shell module is no different than executing a command in shell eg: /bin/sh
  register: grub_file # store the result of a shell command in grub_file
  failed_when: False # silently fail when there are errors

- name: update grub
  command: “sudo update-grub -y” # different from shell module as this does not have access to variables like $HOME etc..
  when: grub_file.rc != 0
  
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Update all packages to the latest version
  apt:
    upgrade: dist
